### ISSUE TITLE
AttributeError: 'Slider' object has no attribute 'knob'

### ISSUE THREAD

**Issue by ShadityZ** [pokepetter/ursina#414] opened 2022-05-09 09:46 UTC
When using the prefab Slider, I often get this error:
```
File "/home/kanj/.local/lib/python3.10/site-packages/vitrix_engine-4.2.0-py3.10.egg/vitrix_engine/prefabs/slider.py", line 91, in update
    if self.knob.dragging:
AttributeError: 'Slider' object has no attribute 'knob'
```
Not only that, but I sometimes get another error that states something with the Color class has gone wrong, again related to the Slider. Is the Slider class a work or progress, or is this a bug? I have tried with the github version as well as the v4.1.1 on PyPi. Any ideas?

**Comment by pokepetter** [comment] 2022-05-09 09:54
Can't reproduce. Can you provide a minimal reproducible example?

**Comment by ShadityZ** [comment] 2022-05-09 10:04
I've got this:

**Comment by pokepetter** [comment] 2022-05-09 13:05
That's not good enough. I do suspect you're using an outdated ursina version though, compared to the github version.

**Comment by ShadityZ** [comment] 2022-05-10 08:56
> That's not good enough. I do suspect you're using an outdated ursina version though, compared to the github version.

What else do I need to send? I am using the latest commit of the github master branch. I've tested on multiple different Ursina versions, and the version doesn't seem to be affecting anything

**Comment by pokepetter** [comment] 2022-05-10 10:50
First of all, I can't see a slider anywhere. If I run your code, I get a menu, but no error.
When installing, make sure it doesn't just reinstall the cached version

**Comment by pokepetter** [comment] 2022-05-10 12:47
https://stackoverflow.com/questions/19548957/can-i-force-pip-to-reinstall-the-current-version

**Comment by pokepetter** [comment] 2022-05-11 12:39
No, it's not there.

**Comment by y2bad** [comment] 2022-05-11 14:04
something similar happened to me, i think sometimes the update function is called before the initializing function has finished running

**Comment by ShadityZ** [comment] 2022-05-12 09:23
> No, it's not there.

Sorry. I forgot to include the option menu slider in the code. I have edited the code in the previous post. It is there now.

> something similar happened to me, i think sometimes the update function is called before the initializing function has finished running

I found the same thing, the init funciton happens to be rather long for the slider, and before it is finished, it ends up crashing. I believe the issue is only apparent on lower-end systems as they don't complete the function on time because they are slower than other PCs

**Comment by pokepetter** [comment] 2022-05-12 09:56
Ok, thanks, I've managed to reproduce it now.

**Comment by pokepetter** [comment] 2022-05-12 22:03
Should be fixed.

**Closed by pokepetter** 2022-05-12 22:03 UTC

**Comment by y2bad** [comment] 2022-05-13 14:15
i tested a little bit around and this only happens if the slider (it also happens with other things) is instanced in a thread, otherwise it works fine.
